# wrangler.toml
name = "spenddy"              # any unique name
compatibility_date = "2025-07-12"
main = "src/index.tsx"


# We are *not* shipping a Worker script, just static files
[site]
bucket = "./dist"             # path that vite just produced


# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
